name: Auto Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'dist/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'dist/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: bahmutov/npm-install@v1

      - name: Install
        run: yarn install

      - name: Clean dist
        run: rm -rf dist

      - name: Build
        run: yarn build.github

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: 'build: dist'
          file_pattern: dist/*
          commit_user_name: divlook
          commit_user_email: uihyeon.cha@gmail.com
          push_options: '--force'

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-user-name: divlook
          git-user-email: uihyeon.cha@gmail.com

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
